### ISSUE TITLE
Program crashes when attempting to show breathing notification

### ISSUE THREAD

**Issue by Graphcalibur** [mindfulness-at-the-computer/mindfulness-at-the-computer#289] opened 2018-04-30 11:26 UTC
The program crashes when attempting to show the breathing notification. The log shows this error:

![image](https://user-images.githubusercontent.com/38370960/39425148-a3d5b516-4cac-11e8-98e0-3b1dd4549bc3.png)

This occurs on the latest version of the program (commit 259b5b1)

**Comment by SunyataZero** [comment] 2018-04-30 12:16
@Graphcalibur Thank you for reporting this! I'm glad you found this error, you are running directly from source right?

**Comment by Graphcalibur** [comment] 2018-04-30 14:06
@SunyataZero Yeah

**Comment by SunyataZero** [comment] 2018-04-30 15:08
@Graphcalibur Okay, i think i know what the problem is, again thank you, very good to know. There may be a race condition which isn't seen on my computer, i had my worries about this so i'm grateful that you found it now rather than later, and also took the time to file this issue

**Comment by SunyataZero** [comment] 2018-05-07 10:08
@Graphcalibur Hi, could you try this out now? I think the problem may be fixed in a recent commit

**Comment by Graphcalibur** [comment] 2018-05-07 12:48
@SunyataZero Yup, the program shows the breathing dialog without crashing.

**Comment by SunyataZero** [comment] 2018-05-07 13:52
@Graphcalibur Thanks for helping us! And please don't hesitate to contact us if you have a feature suggestion or find another bug in the program. We are still in alpha so ideas for improving the software are most welcome. Do you have any ideas now what could be improved and what is already working well for you?

**Closed by SunyataZero** 2018-05-07 13:52 UTC
Labels: bug
